### ISSUE TITLE
大神,这个DEMO在API 18 或者 16 报错闪退

### ISSUE THREAD

**Issue by zzh3321** [linxin6560/DetailScrollView#1]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                            java.lang.NullPointerException
                                                                                                at android.widget.ScrollBarDrawable.setAlpha(ScrollBarDrawable.java:221)
                                                                                                at android.view.View.onDrawScrollBars(View.java:11542)
                                                                                                at android.view.View.draw(View.java:13950)
                                                                                                at android.view.View.getDisplayList(View.java:12838)
                                                                                                at android.view.View.getDisplayList(View.java:12880)
                                                                                                at android.view.View.draw(View.java:13657)
                                                                                                at android.view.ViewGroup.drawChild(ViewGroup.java:3086)
                                                                                                at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2923)
                                                                                                at android.view.View.getDisplayList(View.java:12833)
                                                                                                at android.view.View.getDisplayList(View.java:12880)

**Comment by zzh3321** [comment]
setWillNotDraw();是这个方法的问题
目前找到一个办法是在这个方法上加上API版本的判断
但是这样就不会显示滑动条
不知道有没有更好的解决办法?

**Comment by linxin6560** [comment]
有没有具体的机型和型号。。我在三星的手机上面有遇到类似的情况，我现在的做法是加try-catch
